# Generated by Django 4.2.16 on 2026-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=64, unique=True, verbose_name='券码')),
                ('redemption_id', models.BigIntegerField(verbose_name='兑换单ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('item_id', models.BigIntegerField(verbose_name='商品ID')),
                ('item_name', models.CharField(max_length=64, verbose_name='权益名称快照')),
                ('category', models.SmallIntegerField(verbose_name='品类')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'mall_voucher',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='mall_vouche_user_id_b0eb9b_idx'), models.Index(fields=['expire_at'], name='mall_vouche_expire__30e3d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MallRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_no', models.CharField(max_length=64, unique=True, verbose_name='兑换单号')),
                ('request_id', models.CharField(max_length=64, unique=True, verbose_name='幂等请求ID(客户端UUID)')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('item_id', models.BigIntegerField(verbose_name='商品ID')),
                ('category', models.SmallIntegerField(verbose_name='品类快照')),
                ('item_name', models.CharField(max_length=64, verbose_name='商品名快照')),
                ('points_price', models.BigIntegerField(verbose_name='扣减积分快照')),
                ('quantity', models.IntegerField(default=1, verbose_name='兑换份数')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
            ],
            options={
                'db_table': 'mall_redemption',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='mall_redemp_user_id_94f440_idx'), models.Index(fields=['user_id', 'category', 'created_at'], name='mall_redemp_user_id_f2d2ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='MallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权益名称')),
                ('category', models.SmallIntegerField(choices=[(1, '观影代金券'), (2, '免费观影票'), (3, '小食套餐券'), (4, '优先场券'), (5, '双人套票')], default=1, verbose_name='品类')),
                ('cover_url', models.CharField(blank=True, default='', max_length=512, verbose_name='头图URL(空则前端回退示意图)')),
                ('points_price', models.BigIntegerField(verbose_name='兑换所需积分')),
                ('origin_price_fen', models.BigIntegerField(default=0, verbose_name='原价对照(分,0=无对照)')),
                ('stock_total', models.IntegerField(default=0, verbose_name='上架总库存(份)')),
                ('stock', models.IntegerField(default=0, verbose_name='剩余库存(份)')),
                ('daily_limit', models.IntegerField(default=3, verbose_name='每人每日同品类上限(张,0=不限)')),
                ('expire_days', models.IntegerField(default=30, verbose_name='券有效期(天)')),
                ('badge', models.CharField(blank=True, default='', max_length=8, verbose_name='角标 HOT/NEW/空')),
                ('description', models.TextField(blank=True, default='', verbose_name='权益说明')),
                ('notes', models.TextField(blank=True, default='', verbose_name='兑换须知')),
                ('applicable', models.TextField(blank=True, default='', verbose_name='适用影院/范围说明')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=0, verbose_name='上下架')),
                ('sort', models.IntegerField(default=0, verbose_name='排序(小者前)')),
                ('deleted', models.SmallIntegerField(default=0, verbose_name='软删')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mall_item',
                'ordering': ['sort', '-id'],
                'indexes': [models.Index(fields=['status', 'deleted', 'sort'], name='mall_item_status_dd461a_idx'), models.Index(fields=['category'], name='mall_item_categor_bbf27e_idx')],
            },
        ),
    ]
