# Generated by Django 4.2.16 on 2026-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_seed_default_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallitem',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '观影代金券'), (2, '免费观影票'), (3, '小食套餐券')], default=1, verbose_name='品类'),
        ),
    ]
