# Generated by Django 4.2.16 on 2026-10-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_alter_mallitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallitem',
            name='face_value_fen',
            field=models.BigIntegerField(default=0, verbose_name='券面额(分,抵扣额)'),
        ),
        migrations.AddField(
            model_name='mallitem',
            name='use_threshold_fen',
            field=models.BigIntegerField(default=0, verbose_name='使用门槛(分,票面应付满此额可用,0=无门槛)'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='order_ext_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='占用/核销订单号'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='threshold_fen',
            field=models.BigIntegerField(default=0, verbose_name='使用门槛快照(分,0=无门槛)'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='value_fen',
            field=models.BigIntegerField(default=0, verbose_name='券面额快照(分)'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['order_ext_no'], name='mall_vouche_order_e_4c7fde_idx'),
        ),
    ]
