# Generated by Django 4.2.16 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MahuaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='可用余额(分)')),
                ('frozen', models.BigIntegerField(default=0, verbose_name='冻结(分)')),
                ('total_recharge', models.BigIntegerField(default=0, verbose_name='累计充值')),
                ('total_dispatch', models.BigIntegerField(default=0, verbose_name='累计放单(分)')),
                ('snapshot_at', models.DateTimeField(verbose_name='快照时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mahua_account',
            },
        ),
        migrations.CreateModel(
            name='MahuaRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='我方充值单号')),
                ('mahua_order_no', models.CharField(max_length=64, null=True, verbose_name='麻花充值单号')),
                ('amount', models.BigIntegerField(verbose_name='金额(分)')),
                ('channel', models.CharField(max_length=32, null=True, verbose_name='渠道')),
                ('status', models.SmallIntegerField(default=0, verbose_name='0处理中 1成功 2失败')),
                ('paid_at', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mahua_recharge',
            },
        ),
        migrations.CreateModel(
            name='MahuaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_type', models.CharField(max_length=32, verbose_name='order/dispute/movie/schedule')),
                ('dedup_key', models.CharField(max_length=128, unique=True, verbose_name='幂等键')),
                ('payload', models.JSONField(verbose_name='报文')),
                ('handle_status', models.SmallIntegerField(default=0, verbose_name='0待处理 1成功 2失败 3重复忽略')),
                ('error_msg', models.CharField(max_length=512, null=True, verbose_name='错误信息')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'db_table': 'mahua_callback_log',
                'indexes': [models.Index(fields=['biz_type', 'received_at'], name='mahua_callb_biz_typ_9b10c1_idx')],
            },
        ),
    ]
