# Generated by Django 4.2.16 on 2026-10-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upadapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_biz_no', models.CharField(max_length=64, unique=True, verbose_name='幂等号')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('img_sha256', models.CharField(max_length=64, verbose_name='图片指纹(不落原图)')),
                ('img_size', models.IntegerField(default=0, verbose_name='图片字节数')),
                ('rtn_code', models.CharField(max_length=16, null=True, verbose_name='麻花码')),
                ('rtn_msg', models.CharField(max_length=128, null=True, verbose_name='麻花文案')),
                ('status', models.SmallIntegerField(choices=[(0, '识别中'), (1, '唯一匹配'), (2, '多候选'), (3, '未匹配'), (4, '失败')], default=0, verbose_name='状态')),
                ('error_stage', models.CharField(max_length=16, null=True, verbose_name='归一化失败阶段')),
                ('up_film_id', models.CharField(max_length=64, null=True, verbose_name='麻花影片ID')),
                ('up_cinema_id', models.CharField(max_length=64, null=True, verbose_name='麻花影院ID')),
                ('up_show_id', models.CharField(max_length=64, null=True, verbose_name='麻花排片ID')),
                ('film_std_id', models.CharField(max_length=64, null=True, verbose_name='影片标准ID')),
                ('cinema_std_id', models.CharField(max_length=64, null=True, verbose_name='影院标准ID')),
                ('movie_id', models.BigIntegerField(null=True, verbose_name='内部影片ID')),
                ('cinema_id', models.BigIntegerField(null=True, verbose_name='内部影院ID')),
                ('schedule_id', models.BigIntegerField(null=True, verbose_name='内部排片ID')),
                ('recognized_json', models.JSONField(null=True, verbose_name='识别信息原文')),
                ('schedule_json', models.JSONField(null=True, verbose_name='场次信息原文')),
                ('seats_json', models.JSONField(null=True, verbose_name='识别座位[{seatNo,price元}]')),
                ('candidates_json', models.JSONField(null=True, verbose_name='候选排片[]')),
                ('raw_response_json', models.JSONField(null=True, verbose_name='完整rtnData留档')),
                ('seat_count', models.IntegerField(default=0, verbose_name='座位数(flat上浮用)')),
                ('evaluate_fen', models.BigIntegerField(null=True, verbose_name='麻花特惠估价=成本(分,未上浮)')),
                ('sell_fen', models.BigIntegerField(null=True, verbose_name='上浮后售价=成交价/应付(分)')),
                ('face_total_fen', models.BigIntegerField(null=True, verbose_name='座位原价合计(分)')),
                ('save_fen', models.BigIntegerField(null=True, verbose_name='省(分,原价-售价)')),
                ('matched_index', models.SmallIntegerField(null=True, verbose_name='候选选定下标')),
                ('charged_fen', models.IntegerField(default=0, verbose_name='本次计费(分,成功=1)')),
                ('cost_ms', models.IntegerField(null=True, verbose_name='调用耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'ocr_session',
                'indexes': [models.Index(fields=['user_id'], name='ocr_session_user_id_ab05a9_idx'), models.Index(fields=['status', 'created_at'], name='ocr_session_status_9ac784_idx'), models.Index(fields=['up_show_id'], name='ocr_session_up_show_5da99e_idx'), models.Index(fields=['img_sha256'], name='ocr_session_img_sha_761472_idx')],
            },
        ),
    ]
