# Generated by Django 4.2.16 on 2026-10-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upadapter', '0002_ocrsession'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ocrsession',
            index=models.Index(fields=['created_at'], name='ocr_session_created_2f2832_idx'),
        ),
    ]
