# Generated by Django 4.2.16 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(verbose_name='对账日期')),
                ('source', models.CharField(max_length=16, verbose_name='来源 MAHUA/PAY/LOCAL')),
                ('order_ext_no', models.CharField(max_length=64, null=True, verbose_name='订单号')),
                ('field', models.CharField(max_length=64, verbose_name='字段')),
                ('local_val', models.CharField(max_length=128, null=True, verbose_name='本地值')),
                ('remote_val', models.CharField(max_length=128, null=True, verbose_name='远端值')),
                ('diff_type', models.CharField(max_length=32, verbose_name='差异类型')),
                ('handle_status', models.SmallIntegerField(default=0, verbose_name='处理状态 0待处理 1已处理 2忽略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'reconciliation_diff',
                'indexes': [models.Index(fields=['bill_date', 'handle_status'], name='reconciliat_bill_da_12d8d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=64, verbose_name='任务名')),
                ('shard', models.IntegerField(default=0, verbose_name='分片')),
                ('biz_date', models.DateField(null=True, verbose_name='业务日期')),
                ('status', models.SmallIntegerField(verbose_name='0运行中 1成功 2失败')),
                ('rows_affected', models.IntegerField(default=0, verbose_name='影响行数')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='结束时间')),
            ],
            options={
                'db_table': 'job_run_log',
                'indexes': [models.Index(fields=['job_name', 'biz_date'], name='job_run_log_job_nam_b39075_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_type', models.CharField(max_length=32, verbose_name='业务类型')),
                ('biz_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('result_snapshot', models.JSONField(null=True, verbose_name='结果快照')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'idempotent_record',
                'unique_together': {('biz_type', 'biz_key')},
            },
        ),
    ]
