# Generated by Django 4.2.16 on 2026-10-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='登录名')),
                ('password', models.CharField(max_length=128, verbose_name='密码哈希')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称')),
                ('is_active', models.SmallIntegerField(default=1, verbose_name='1启用 0停用')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='AdminOpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField(verbose_name='管理员ID')),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('target', models.CharField(blank=True, max_length=128, null=True, verbose_name='对象标识')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='详情快照')),
                ('ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='来源IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'admin_op_log',
                'indexes': [models.Index(fields=['admin_id', 'created_at'], name='admin_op_lo_admin_i_2f3065_idx')],
            },
        ),
    ]
