# Generated by Django 4.2.16 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.SmallIntegerField(verbose_name='1全局 2影院 3影片 4活动')),
                ('scope_ref', models.CharField(max_length=64, null=True, verbose_name='范围引用')),
                ('mode', models.SmallIntegerField(verbose_name='1差价 2比例')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='费率')),
                ('fixed_diff', models.BigIntegerField(null=True, verbose_name='固定差价(分)')),
                ('min_amt', models.BigIntegerField(default=0, verbose_name='最低佣金')),
                ('max_amt', models.BigIntegerField(default=0, verbose_name='最高佣金')),
                ('effective_from', models.DateTimeField(verbose_name='生效时间')),
                ('effective_to', models.DateTimeField(null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'commission_rule',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='用户ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='可提余额(分)')),
                ('frozen', models.BigIntegerField(default=0, verbose_name='提现冻结(分)')),
                ('total_income', models.BigIntegerField(default=0, verbose_name='累计收入')),
                ('total_withdraw', models.BigIntegerField(default=0, verbose_name='累计提现')),
                ('version', models.IntegerField(default=0, verbose_name='CAS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_no', models.CharField(max_length=64, unique=True, verbose_name='提现单号')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('amount', models.BigIntegerField(verbose_name='金额(分)')),
                ('fee', models.BigIntegerField(default=0, verbose_name='手续费(分)')),
                ('channel', models.SmallIntegerField(verbose_name='1微信零钱 2银行卡')),
                ('account_ref', models.CharField(max_length=128, null=True, verbose_name='账户引用')),
                ('realname_verified', models.SmallIntegerField(default=0, verbose_name='是否实名')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('pay_no', models.CharField(max_length=64, null=True, verbose_name='代付流水')),
                ('callback_raw', models.JSONField(null=True, verbose_name='回调原文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'withdrawal',
                'indexes': [models.Index(fields=['user_id', 'status'], name='withdrawal_user_id_7c2826_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.BigIntegerField(verbose_name='钱包ID')),
                ('biz_type', models.SmallIntegerField(verbose_name='业务类型')),
                ('amount', models.BigIntegerField(verbose_name='带符号金额(分)')),
                ('ref_no', models.CharField(max_length=64, null=True, verbose_name='关联单号')),
                ('balance_after', models.BigIntegerField(verbose_name='变动后余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'wallet_txn',
                'indexes': [models.Index(fields=['wallet_id', 'created_at'], name='wallet_txn_wallet__ee3090_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('type', models.CharField(max_length=32, verbose_name='事件类型')),
                ('score', models.IntegerField(default=0, verbose_name='评分')),
                ('action', models.SmallIntegerField(verbose_name='1放行 2冻结佣金 3人工审')),
                ('ref', models.CharField(max_length=64, null=True, verbose_name='引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'risk_event',
                'indexes': [models.Index(fields=['user_id'], name='risk_event_user_id_eaf6c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='用户ID')),
                ('invite_code', models.CharField(max_length=16, unique=True, verbose_name='推广码')),
                ('parent_id', models.BigIntegerField(null=True, verbose_name='直属上级')),
                ('grand_id', models.BigIntegerField(null=True, verbose_name='间接上级')),
                ('level_path', models.CharField(max_length=255, verbose_name='物化路径')),
                ('bind_at', models.DateTimeField(verbose_name='绑定时间')),
                ('source', models.SmallIntegerField(verbose_name='1码 2小程序码 3口令')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'distributor',
                'indexes': [models.Index(fields=['parent_id'], name='distributor_parent__b1b1c9_idx'), models.Index(fields=['level_path'], name='distributor_level_p_40b075_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_no', models.CharField(max_length=64, unique=True, verbose_name='流水号')),
                ('order_id', models.BigIntegerField(verbose_name='订单ID')),
                ('buyer_id', models.BigIntegerField(verbose_name='下单人')),
                ('promoter_id', models.BigIntegerField(verbose_name='得佣人')),
                ('level', models.SmallIntegerField(verbose_name='1直属 2间接')),
                ('base_amount', models.BigIntegerField(verbose_name='售价(分)')),
                ('settle_amount', models.BigIntegerField(verbose_name='结算价(分)')),
                ('commission_amount', models.BigIntegerField(verbose_name='佣金(分)')),
                ('type', models.SmallIntegerField(verbose_name='1收入 2扣回')),
                ('status', models.SmallIntegerField(verbose_name='1在途 2已结算 3已失效')),
                ('settle_at', models.DateTimeField(null=True, verbose_name='结算时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'commission_record',
                'indexes': [models.Index(fields=['promoter_id', 'status'], name='commission__promote_5b0bc8_idx')],
                'unique_together': {('order_id', 'promoter_id', 'level', 'type')},
            },
        ),
    ]
