# Generated by Django 4.2.16 on 2026-10-07 12:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='滚动过期锚点'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='可用观影金(分)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='frozen',
            field=models.BigIntegerField(default=0, verbose_name='下单抵扣冻结(分)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_income',
            field=models.BigIntegerField(default=0, verbose_name='累计获得观影金(分)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_withdraw',
            field=models.BigIntegerField(default=0, verbose_name='累计提现(历史遗留·停用)'),
        ),
        migrations.CreateModel(
            name='DeductRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规则名')),
                ('scope', models.SmallIntegerField(default=1, verbose_name='1全局 2活动')),
                ('scope_ref', models.CharField(blank=True, max_length=64, null=True, verbose_name='活动引用')),
                ('max_deduct_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.5000'), max_digits=5, verbose_name='单笔最高抵扣比例')),
                ('min_self_pay', models.BigIntegerField(default=100, verbose_name='最低自付(分)')),
                ('per_order_cap', models.BigIntegerField(default=0, verbose_name='单笔抵扣上限(分,0=不限)')),
                ('daily_deduct_cap', models.BigIntegerField(default=0, verbose_name='每人每日抵扣上限(分,0=不限)')),
                ('expire_days', models.IntegerField(default=365, verbose_name='观影金有效期天数(0=不过期)')),
                ('allow_grand', models.SmallIntegerField(default=0, verbose_name='二级分佣开关(0关1开)')),
                ('stack_with_coupon', models.SmallIntegerField(default=0, verbose_name='可与优惠券叠加(0二选一)')),
                ('is_active', models.SmallIntegerField(default=1, verbose_name='启用')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'deduct_rule',
                'indexes': [models.Index(fields=['scope', 'is_active'], name='deduct_rule_scope_ba1e64_idx')],
            },
        ),
    ]
