# Generated by Django 4.2.16 on 2026-10-07 16:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_wallet_expire_at_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductrule',
            name='fen_per_point',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=6, verbose_name='兑换率(1积分抵扣多少分)'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='growth',
            field=models.BigIntegerField(default=0, verbose_name='成长值(累计获得积分·只增·驱动等级)'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_earn_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次签到/入账日'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='streak',
            field=models.IntegerField(default=0, verbose_name='连续签到天数'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='tier',
            field=models.SmallIntegerField(default=0, verbose_name='会员等级(0~4)'),
        ),
        migrations.AddField(
            model_name='wallettxn',
            name='remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='展示文案'),
        ),
        migrations.AddField(
            model_name='wallettxn',
            name='scene',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='获取子类(仅入账用)'),
        ),
        migrations.AlterField(
            model_name='deductrule',
            name='allow_grand',
            field=models.SmallIntegerField(default=0, verbose_name='【已废弃】二级分佣开关'),
        ),
        migrations.AlterField(
            model_name='deductrule',
            name='expire_days',
            field=models.IntegerField(default=365, verbose_name='积分有效期天数(0=不过期)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='可用积分'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='frozen',
            field=models.BigIntegerField(default=0, verbose_name='下单抵扣冻结(积分)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_income',
            field=models.BigIntegerField(default=0, verbose_name='累计获得积分'),
        ),
        migrations.AlterField(
            model_name='wallettxn',
            name='amount',
            field=models.BigIntegerField(verbose_name='带符号金额(积分)'),
        ),
        migrations.AlterField(
            model_name='wallettxn',
            name='balance_after',
            field=models.BigIntegerField(verbose_name='变动后余额(积分)'),
        ),
        migrations.AlterField(
            model_name='wallettxn',
            name='wallet_id',
            field=models.BigIntegerField(verbose_name='账户ID'),
        ),
    ]
