# Generated by Django 4.2.16 on 2026-10-10 16:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_reset_wallet_balance_for_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(unique=True, verbose_name='等级序号(0~N)')),
                ('name', models.CharField(max_length=32, verbose_name='等级名称')),
                ('growth_min', models.BigIntegerField(default=0, verbose_name='达到此成长值解锁')),
                ('consume_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='该等级消费返利率(0=沿用全局 CONSUME_RATE)')),
                ('color', models.CharField(blank=True, default='', max_length=16, verbose_name='展示色(如 #ff2f6d)')),
                ('perks', models.TextField(blank=True, default='', verbose_name='权益说明(纯文本/JSON 由前端约定)')),
                ('is_active', models.SmallIntegerField(default=1, verbose_name='1启用 0停用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序(小→大)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'member_level',
                'ordering': ['level'],
            },
        ),
    ]
