# Generated by Django 4.2.16 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_token', models.CharField(max_length=36, verbose_name='锁token')),
                ('schedule_id', models.BigIntegerField(verbose_name='排片ID')),
                ('seat_no', models.CharField(max_length=32, verbose_name='座位号 如7排8座')),
            ],
            options={
                'db_table': 'seat_lock_item',
                'indexes': [models.Index(fields=['lock_token'], name='seat_lock_i_lock_to_d7ba2b_idx')],
                'unique_together': {('schedule_id', 'seat_no')},
            },
        ),
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_token', models.CharField(max_length=36, unique=True, verbose_name='锁token')),
                ('schedule_id', models.BigIntegerField(verbose_name='排片ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('seats_json', models.JSONField(verbose_name='座位快照')),
                ('seat_count', models.SmallIntegerField(verbose_name='座位数')),
                ('status', models.SmallIntegerField(verbose_name='1占用 2已下单 3已释放 4已过期')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('order_id', models.BigIntegerField(null=True, verbose_name='订单ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'seat_lock',
                'indexes': [models.Index(fields=['schedule_id', 'status'], name='seat_lock_schedul_f76d08_idx'), models.Index(fields=['expire_at'], name='seat_lock_expire__913ebf_idx')],
            },
        ),
    ]
