# Generated by Django 4.2.16 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ext_no', models.CharField(max_length=64, unique=True, verbose_name='幂等订单号')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('schedule_id', models.BigIntegerField(verbose_name='排片ID')),
                ('cinema_id', models.BigIntegerField(verbose_name='影院ID')),
                ('movie_id', models.BigIntegerField(verbose_name='影片ID')),
                ('up_schedule_id', models.CharField(max_length=64, verbose_name='麻花排片ID快照')),
                ('seats_json', models.JSONField(verbose_name='座位快照')),
                ('seat_count', models.SmallIntegerField(verbose_name='座位数')),
                ('ticket_amount', models.BigIntegerField(verbose_name='票面总额(分)')),
                ('service_fee', models.BigIntegerField(default=0, verbose_name='服务费(分)')),
                ('discount_amount', models.BigIntegerField(default=0, verbose_name='优惠(分)')),
                ('pay_amount', models.BigIntegerField(verbose_name='实付(分)')),
                ('settle_amount', models.BigIntegerField(null=True, verbose_name='结算价(分)')),
                ('mobile', models.CharField(max_length=20, verbose_name='取票手机')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('pay_status', models.SmallIntegerField(default=0, verbose_name='0未付 1已付 2已退')),
                ('lock_token', models.CharField(max_length=36, null=True, verbose_name='锁token')),
                ('promoter_id', models.BigIntegerField(null=True, verbose_name='推广人')),
                ('confirmed_at', models.DateTimeField(null=True, verbose_name='确认收货时间')),
                ('close_reason', models.CharField(max_length=64, null=True, verbose_name='关闭原因')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('deleted', models.SmallIntegerField(default=0, verbose_name='软删')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'ticket_order',
                'indexes': [models.Index(fields=['user_id', 'status'], name='ticket_orde_user_id_74ca24_idx'), models.Index(fields=['status', 'created_at'], name='ticket_orde_status_c8282a_idx'), models.Index(fields=['promoter_id'], name='ticket_orde_promote_e75d6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='订单ID')),
                ('seat_no', models.CharField(max_length=32, verbose_name='座位号')),
                ('ticket_code', models.CharField(max_length=128, null=True, verbose_name='取票码')),
                ('barcode', models.CharField(max_length=255, null=True, verbose_name='二维码')),
                ('status', models.SmallIntegerField(default=1, verbose_name='1待取 2已取 3已观影 4已退')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ticket',
                'indexes': [models.Index(fields=['order_id'], name='ticket_order_i_5e884d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='订单ID')),
                ('pay_no', models.CharField(max_length=64, unique=True, verbose_name='支付流水号')),
                ('channel', models.CharField(default='WX', max_length=16, verbose_name='渠道')),
                ('amount', models.BigIntegerField(verbose_name='金额(分)')),
                ('status', models.SmallIntegerField(verbose_name='0待付 1成功 2失败 3已退')),
                ('callback_raw', models.JSONField(null=True, verbose_name='回调原文')),
                ('paid_at', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'order_payment',
                'indexes': [models.Index(fields=['order_id'], name='order_payme_order_i_1ea8bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MahuaDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ext_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('mahua_order_no', models.CharField(max_length=64, null=True, verbose_name='麻花放单号')),
                ('request_body', models.JSONField(verbose_name='请求体')),
                ('response_body', models.JSONField(null=True, verbose_name='响应体')),
                ('dispatch_status', models.SmallIntegerField(default=0, verbose_name='放单状态')),
                ('ticket_code', models.CharField(max_length=128, null=True, verbose_name='取票码')),
                ('barcode', models.CharField(max_length=255, null=True, verbose_name='二维码')),
                ('last_query_at', models.DateTimeField(null=True, verbose_name='最近查询时间')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mahua_dispatch',
                'indexes': [models.Index(fields=['mahua_order_no'], name='mahua_dispa_mahua_o_540e8d_idx')],
            },
        ),
    ]
