# Generated by Django 4.2.16 on 2026-10-07 10:21

from django.db import migrations, models


def backfill_show_start_at(apps, schema_editor):
    """存量订单回填开场时间快照（取排片表 start_at，查不到保持空）。"""
    TicketOrder = apps.get_model('order', 'TicketOrder')
    Schedule = apps.get_model('catalog', 'Schedule')
    starts = dict(Schedule.objects.values_list('id', 'start_at'))
    for order in TicketOrder.objects.filter(show_start_at__isnull=True):
        start_at = starts.get(order.schedule_id)
        if start_at:
            TicketOrder.objects.filter(id=order.id).update(show_start_at=start_at)


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ticketorder_buy_mode'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='show_start_at',
            field=models.DateTimeField(null=True, verbose_name='开场时间快照(建单时)'),
        ),
        migrations.RunPython(backfill_show_start_at, migrations.RunPython.noop),
    ]
