# Generated by Django 4.2.16 on 2026-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ticketorder_show_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='point_deduct',
            field=models.BigIntegerField(default=0, verbose_name='本单抵扣消耗的积分'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='point_deduct_value',
            field=models.BigIntegerField(default=0, verbose_name='积分抵扣折算金额(分)'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='pay_amount',
            field=models.BigIntegerField(verbose_name='实付(分,微信现金)'),
        ),
    ]
