# Generated by Django 4.2.16 on 2026-10-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ticketorder_point_deduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='is_read',
            field=models.SmallIntegerField(default=0, verbose_name='通知是否已读(0未读1已读)'),
        ),
    ]
