# Generated by Django 4.2.16 on 2026-10-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ticketorder_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='point_deduct',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='point_deduct_value',
        ),
    ]
