# Generated by Django 4.2.16 on 2026-10-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_ticketorder_point_deduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='voucher_amount',
            field=models.BigIntegerField(default=0, verbose_name='代金券抵扣(分)'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='voucher_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='使用的代金券码(空=未用)'),
        ),
    ]
