# Generated by Django 4.2.16 on 2026-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='绑定手机号(唯一)'),
        ),
    ]
