# Generated by Django 4.2.16 on 2026-09-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='std_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='国标行政区划码'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(max_length=16, unique=True, verbose_name='麻花城市ID'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['std_code'], name='city_std_cod_50f5c7_idx'),
        ),
    ]
