# Generated by Django 4.2.16 on 2026-09-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_city_std_code_alter_city_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='presale',
            field=models.SmallIntegerField(default=0, verbose_name='预售/特惠 1是 0否'),
        ),
        migrations.AddField(
            model_name='movie',
            name='want_count',
            field=models.IntegerField(default=0, verbose_name='想看人数'),
        ),
    ]
