# Generated by Django 4.2.16 on 2026-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_movie_presale_movie_want_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='origin_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='原价(分)'),
        ),
    ]
