# Generated by Django 4.2.16 on 2026-09-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_schedule_origin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='stopsell_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='停售时间(麻花特惠口径,空则回退start_at)'),
        ),
    ]
