# Generated by Django 4.2.16 on 2026-10-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_schedule_stopsell_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='麻花确认无排片时间(按影片查影院返回权威空集时打标)'),
        ),
    ]
