# Generated by Django 4.2.16 on 2026-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_schedule_raw_price_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规则名')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级(小者先)')),
                ('is_active', models.SmallIntegerField(default=1, verbose_name='1启用 0停用')),
                ('is_fallback', models.SmallIntegerField(default=0, verbose_name='是否兜底规则')),
                ('movie_ids', models.JSONField(blank=True, null=True, verbose_name='影片ID列表')),
                ('brands', models.JSONField(blank=True, null=True, verbose_name='院线品牌列表')),
                ('city_codes', models.JSONField(blank=True, null=True, verbose_name='城市码列表')),
                ('hall_types', models.JSONField(blank=True, null=True, verbose_name='影厅类型/show_version列表')),
                ('weekday_in', models.JSONField(blank=True, null=True, verbose_name='星期几(1-7)列表')),
                ('hour_from', models.SmallIntegerField(blank=True, null=True, verbose_name='时段起(0-23)')),
                ('hour_to', models.SmallIntegerField(blank=True, null=True, verbose_name='时段止(0-23)')),
                ('mode', models.CharField(default='rate', max_length=8, verbose_name='加价方式')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='比例(0.12=12%)')),
                ('flat_fen', models.BigIntegerField(blank=True, null=True, verbose_name='固定加价(分/张)')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效起')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='生效止')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('deleted', models.SmallIntegerField(default=0, verbose_name='软删')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'markup_rule',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
