# Generated by Django 4.2.16 on 2026-10-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_markuprule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='本月推荐', max_length=32, verbose_name='栏目标题')),
                ('max_show', models.SmallIntegerField(default=6, verbose_name='最多展示条数')),
                ('fallback_top4', models.SmallIntegerField(default=1, verbose_name='空位回退自动Top4 1是 0否')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'recommend_section',
            },
        ),
        migrations.CreateModel(
            name='RecommendSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(default='movie', max_length=8, verbose_name='movie/banner')),
                ('movie_id', models.BigIntegerField(blank=True, null=True, verbose_name='内部影片ID(Movie.id)')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题(banner用)')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='副标题(banner用)')),
                ('cta', models.CharField(blank=True, max_length=64, null=True, verbose_name='按钮文案(banner用)')),
                ('bg', models.CharField(blank=True, max_length=255, null=True, verbose_name='底图渐变(banner用)')),
                ('image_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='自定义底图URL')),
                ('badge', models.CharField(blank=True, max_length=32, null=True, verbose_name='角标文案')),
                ('badge_color', models.CharField(default='pink', max_length=8, verbose_name='pink/blue/gold')),
                ('city_code', models.CharField(default='all', max_length=16, verbose_name='all或麻花城市ID')),
                ('link_type', models.CharField(default='movie', max_length=16, verbose_name='跳转类型')),
                ('link_ref', models.CharField(blank=True, max_length=128, null=True, verbose_name='跳转引用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序(小者前)')),
                ('enabled', models.SmallIntegerField(default=1, verbose_name='1启用 0停用')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效起')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='生效止')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('deleted', models.SmallIntegerField(default=0, verbose_name='软删')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'recommend_slot',
                'ordering': ['sort', 'id'],
                'indexes': [models.Index(fields=['enabled', 'deleted'], name='recommend_s_enabled_b51890_idx')],
            },
        ),
    ]
