# Generated by Django 4.2.16 on 2026-10-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_recommendsection_recommendslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='markuprule',
            name='cinema_ids',
            field=models.JSONField(blank=True, null=True, verbose_name='影院ID列表(内部Cinema.id)'),
        ),
    ]
