# Generated by Django 4.2.16 on 2026-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_markuprule_cinema_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendslot',
            name='banner_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='横版封面URL(影片位轮播用)'),
        ),
    ]
