# Generated by Django 4.2.16 on 2026-10-07 13:44

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_recommendslot_banner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.catalog.models._gen_media_key, max_length=32, unique=True, verbose_name='公开key')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始文件名')),
                ('content_type', models.CharField(max_length=64, verbose_name='MIME')),
                ('size', models.IntegerField(default=0, verbose_name='字节数')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽(px)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高(px)')),
                ('uploaded_by', models.BigIntegerField(blank=True, null=True, verbose_name='上传管理员ID')),
                ('data', models.BinaryField(verbose_name='图片二进制')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'media_asset',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['key'], name='media_asset_key_228bd2_idx')],
            },
        ),
    ]
