# Generated by Django 4.2.16 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_ext_no', models.CharField(max_length=64, unique=True, verbose_name='退款幂等单号')),
                ('order_id', models.BigIntegerField(verbose_name='订单ID')),
                ('type', models.SmallIntegerField(verbose_name='1拦截 2纠纷退票 3出票失败自动退')),
                ('reason', models.CharField(max_length=64, null=True, verbose_name='原因')),
                ('fee', models.BigIntegerField(default=0, verbose_name='手续费(分)')),
                ('refund_amount', models.BigIntegerField(verbose_name='退回金额(分)')),
                ('mahua_refund_no', models.CharField(max_length=64, null=True, verbose_name='麻花退款号')),
                ('wx_refund_no', models.CharField(max_length=64, null=True, verbose_name='微信退款号')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'refund',
                'indexes': [models.Index(fields=['order_id'], name='refund_order_i_b4b7e7_idx'), models.Index(fields=['status'], name='refund_status_1fc04e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisputeMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.BigIntegerField(verbose_name='纠纷ID')),
                ('from_role', models.SmallIntegerField(verbose_name='1用户 2平台 3麻花客服')),
                ('content', models.CharField(max_length=1024, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'dispute_msg',
                'indexes': [models.Index(fields=['dispute_id'], name='dispute_msg_dispute_c9777f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='订单ID')),
                ('refund_id', models.BigIntegerField(null=True, verbose_name='退款单ID')),
                ('up_dispute_no', models.CharField(max_length=64, null=True, verbose_name='麻花纠纷单号')),
                ('reason_code', models.CharField(max_length=32, verbose_name='纠纷原因码')),
                ('reason_text', models.CharField(max_length=128, null=True, verbose_name='原因文本')),
                ('status', models.SmallIntegerField(verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'dispute',
                'indexes': [models.Index(fields=['order_id'], name='dispute_order_i_4361ca_idx'), models.Index(fields=['up_dispute_no'], name='dispute_up_disp_28e095_idx')],
            },
        ),
    ]
