# Generated by Django 4.2.16 on 2026-10-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='微信退款重试次数'),
        ),
    ]
