# Generated by Django 4.2.16 on 2026-10-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('pay_remind', '支付倒计时提醒'), ('pickup_remind', '开场前取票提醒'), ('issued', '出票成功'), ('refunded', '退款成功')], max_length=20, verbose_name='事件类型')),
                ('order_id', models.BigIntegerField(verbose_name='订单ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID(AppUser.id)')),
                ('template_id', models.CharField(blank=True, max_length=64, verbose_name='模板ID快照(发送时以配置为准)')),
                ('due_at', models.DateTimeField(verbose_name='计划发送时刻')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='附加数据(如退款金额/原因)')),
                ('status', models.SmallIntegerField(choices=[(0, '待发'), (1, '成功'), (2, '待重试'), (3, '失败'), (4, '无额度/未配模板'), (5, '跳过'), (6, '处理中')], default=0, verbose_name='状态')),
                ('retry_count', models.SmallIntegerField(default=0, verbose_name='重试次数')),
                ('err_msg', models.CharField(blank=True, max_length=255, verbose_name='最近失败/跳过原因')),
                ('sent_at', models.DateTimeField(null=True, verbose_name='实际发送成功时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'notify_task',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('template_id', models.CharField(max_length=64, verbose_name='微信模板ID')),
                ('count', models.IntegerField(default=0, verbose_name='剩余额度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'subscription_quota',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionquota',
            constraint=models.UniqueConstraint(fields=('user_id', 'template_id'), name='uniq_quota_user_template'),
        ),
        migrations.AddIndex(
            model_name='notifytask',
            index=models.Index(fields=['status', 'due_at'], name='idx_notify_status_due'),
        ),
        migrations.AddConstraint(
            model_name='notifytask',
            constraint=models.UniqueConstraint(fields=('event', 'order_id'), name='uniq_notify_event_order'),
        ),
    ]
